from dataclasses import dataclass, field

from phoenix6 import CANBus, configs, swerve, units


@dataclass
class TunerConstants[
    DriveMotorConfigsT: configs.SupportsSerialization,
    SteerMotorConfigsT: configs.SupportsSerialization,
    EncoderConfigsT: configs.SupportsSerialization,
]:
    """
    Runtime-configurable swerve constants generated by Tuner X.

    The fields mirror the generated ``TunerConstants`` class attributes. Derived
    Phoenix objects are rebuilt in ``__post_init__`` from the selected field values.
    """

    type ModuleConstants = swerve.SwerveModuleConstants[
        DriveMotorConfigsT, SteerMotorConfigsT, EncoderConfigsT
    ]

    # Both sets of gains need to be tuned to your individual robot.
    _steer_gains: configs.Slot0Configs
    _drive_gains: configs.Slot0Configs

    _steer_closed_loop_output: swerve.ClosedLoopOutputType
    _drive_closed_loop_output: swerve.ClosedLoopOutputType
    _drive_motor_type: swerve.DriveMotorArrangement
    _steer_motor_type: swerve.SteerMotorArrangement
    _steer_feedback_type: swerve.SteerFeedbackType

    _slip_current: units.ampere
    _steer_dampening_threshold: units.rotation

    _drive_initial_configs: DriveMotorConfigsT
    _steer_initial_configs: SteerMotorConfigsT
    _encoder_initial_configs: EncoderConfigsT
    _pigeon_configs: configs.Pigeon2Configuration | None

    canbus: CANBus
    speed_at_12_volts: units.meters_per_second

    _couple_ratio: float
    _drive_gear_ratio: float
    _steer_gear_ratio: float
    _wheel_radius: units.meter

    _invert_left_side: bool
    _invert_right_side: bool

    _pigeon_id: int

    _steer_inertia: units.kilogram_square_meter
    _drive_inertia: units.kilogram_square_meter
    _steer_friction_voltage: units.volt
    _drive_friction_voltage: units.volt

    _front_left_drive_motor_id: int
    _front_left_steer_motor_id: int
    _front_left_encoder_id: int
    _front_left_encoder_offset: units.rotation
    _front_left_steer_motor_inverted: bool
    _front_left_encoder_inverted: bool
    _front_left_x_pos: units.meter
    _front_left_y_pos: units.meter

    _front_right_drive_motor_id: int
    _front_right_steer_motor_id: int
    _front_right_encoder_id: int
    _front_right_encoder_offset: units.rotation
    _front_right_steer_motor_inverted: bool
    _front_right_encoder_inverted: bool
    _front_right_x_pos: units.meter
    _front_right_y_pos: units.meter

    _back_left_drive_motor_id: int
    _back_left_steer_motor_id: int
    _back_left_encoder_id: int
    _back_left_encoder_offset: units.rotation
    _back_left_steer_motor_inverted: bool
    _back_left_encoder_inverted: bool
    _back_left_x_pos: units.meter
    _back_left_y_pos: units.meter

    _back_right_drive_motor_id: int
    _back_right_steer_motor_id: int
    _back_right_encoder_id: int
    _back_right_encoder_offset: units.rotation
    _back_right_steer_motor_inverted: bool
    _back_right_encoder_inverted: bool
    _back_right_x_pos: units.meter
    _back_right_y_pos: units.meter

    drivetrain_constants: swerve.SwerveDrivetrainConstants = field(init=False)
    front_left: ModuleConstants = field(init=False)
    front_right: ModuleConstants = field(init=False)
    back_left: ModuleConstants = field(init=False)
    back_right: ModuleConstants = field(init=False)

    def __post_init__(self) -> None:
        self.drivetrain_constants = (
            swerve.SwerveDrivetrainConstants()
            .with_can_bus_name(self.canbus.name)
            .with_pigeon2_id(self._pigeon_id)
            .with_pigeon2_configs(self._pigeon_configs)
        )

        _constants_creator = (
            swerve.SwerveModuleConstantsFactory[
                DriveMotorConfigsT,
                SteerMotorConfigsT,
                EncoderConfigsT,
            ]()
            .with_drive_motor_gear_ratio(self._drive_gear_ratio)
            .with_steer_motor_gear_ratio(self._steer_gear_ratio)
            .with_coupling_gear_ratio(self._couple_ratio)
            .with_wheel_radius(self._wheel_radius)
            .with_steer_motor_gains(self._steer_gains)
            .with_drive_motor_gains(self._drive_gains)
            .with_steer_motor_closed_loop_output(self._steer_closed_loop_output)
            .with_drive_motor_closed_loop_output(self._drive_closed_loop_output)
            .with_slip_current(self._slip_current)
            .with_speed_at12_volts(self.speed_at_12_volts)
            .with_drive_motor_type(self._drive_motor_type)
            .with_steer_motor_type(self._steer_motor_type)
            .with_feedback_source(self._steer_feedback_type)
            .with_drive_motor_initial_configs(self._drive_initial_configs)
            .with_steer_motor_initial_configs(self._steer_initial_configs)
            .with_encoder_initial_configs(self._encoder_initial_configs)
            .with_steer_inertia(self._steer_inertia)
            .with_drive_inertia(self._drive_inertia)
            .with_steer_friction_voltage(self._steer_friction_voltage)
            .with_drive_friction_voltage(self._drive_friction_voltage)
        )

        self.front_left = _constants_creator.create_module_constants(
            self._front_left_steer_motor_id,
            self._front_left_drive_motor_id,
            self._front_left_encoder_id,
            self._front_left_encoder_offset,
            self._front_left_x_pos,
            self._front_left_y_pos,
            self._invert_left_side,
            self._front_left_steer_motor_inverted,
            self._front_left_encoder_inverted,
        )
        self.front_right = _constants_creator.create_module_constants(
            self._front_right_steer_motor_id,
            self._front_right_drive_motor_id,
            self._front_right_encoder_id,
            self._front_right_encoder_offset,
            self._front_right_x_pos,
            self._front_right_y_pos,
            self._invert_right_side,
            self._front_right_steer_motor_inverted,
            self._front_right_encoder_inverted,
        )
        self.back_left = _constants_creator.create_module_constants(
            self._back_left_steer_motor_id,
            self._back_left_drive_motor_id,
            self._back_left_encoder_id,
            self._back_left_encoder_offset,
            self._back_left_x_pos,
            self._back_left_y_pos,
            self._invert_left_side,
            self._back_left_steer_motor_inverted,
            self._back_left_encoder_inverted,
        )
        self.back_right = _constants_creator.create_module_constants(
            self._back_right_steer_motor_id,
            self._back_right_drive_motor_id,
            self._back_right_encoder_id,
            self._back_right_encoder_offset,
            self._back_right_x_pos,
            self._back_right_y_pos,
            self._invert_right_side,
            self._back_right_steer_motor_inverted,
            self._back_right_encoder_inverted,
        )
