from dataclasses import dataclass, field

from phoenix6 import CANBus, configs, signals, swerve, units


@dataclass
class TunerConstants:
    """
    Runtime-configurable swerve constants generated by Tuner X.

    The fields mirror the generated ``TunerConstants`` class attributes. Derived
    Phoenix objects are rebuilt in ``__post_init__`` from the selected field values.
    """

    # Both sets of gains need to be tuned to your individual robot.
    _steer_gains: configs.Slot0Configs = field(
        default_factory=lambda: (
            configs.Slot0Configs()
            .with_k_p(34.876)
            .with_k_i(0)
            .with_k_d(2.5167)
            .with_k_s(0.17715)
            .with_k_v(2.1227)
            .with_k_a(0.10327)
            .with_static_feedforward_sign(
                signals.StaticFeedforwardSignValue.USE_CLOSED_LOOP_SIGN
            )
        )
    )
    _drive_gains: configs.Slot0Configs = field(
        default_factory=lambda: (
            configs.Slot0Configs()
            .with_k_p(0.023983)
            .with_k_d(0)
            .with_k_i(0)
            .with_k_s(0.14118)
            .with_k_v(0.11548)
            .with_k_a(0.0099061)
        )
    )

    _steer_closed_loop_output: swerve.ClosedLoopOutputType = (
        swerve.ClosedLoopOutputType.VOLTAGE
    )
    _drive_closed_loop_output: swerve.ClosedLoopOutputType = (
        swerve.ClosedLoopOutputType.VOLTAGE
    )
    _drive_motor_type: swerve.DriveMotorArrangement = (
        swerve.DriveMotorArrangement.TALON_FX_INTEGRATED
    )
    _steer_motor_type: swerve.SteerMotorArrangement = (
        swerve.SteerMotorArrangement.TALON_FX_INTEGRATED
    )
    _steer_feedback_type: swerve.SteerFeedbackType = (
        swerve.SteerFeedbackType.REMOTE_CANCODER
    )

    _slip_current: units.ampere = 120.0
    _steer_dampening_threshold: units.rotation = 0.05

    _drive_initial_configs: configs.TalonFXConfiguration = field(
        default_factory=configs.TalonFXConfiguration
    )
    _steer_initial_configs: configs.TalonFXConfiguration = field(
        default_factory=lambda: (
            configs.TalonFXConfiguration().with_current_limits(
                configs.CurrentLimitsConfigs()
                .with_stator_current_limit(60.0)
                .with_stator_current_limit_enable(True)
            )
        )
    )
    _encoder_initial_configs: configs.CANcoderConfiguration = field(
        default_factory=configs.CANcoderConfiguration
    )
    _pigeon_configs: configs.Pigeon2Configuration | None = None

    canbus: CANBus = field(default_factory=lambda: CANBus("", "./logs/example.hoot"))
    speed_at_12_volts: units.meters_per_second = 5.23

    _couple_ratio: float = 3.125
    _drive_gear_ratio: float = 5.902777777777778
    _steer_gear_ratio: float = 18.75
    _wheel_radius: units.meter = 0.0508

    _invert_left_side: bool = False
    _invert_right_side: bool = True

    _pigeon_id: int = 0

    _steer_inertia: units.kilogram_square_meter = 0.01
    _drive_inertia: units.kilogram_square_meter = 0.01
    _steer_friction_voltage: units.volt = 0.2
    _drive_friction_voltage: units.volt = 0.2

    _front_left_drive_motor_id: int = 1
    _front_left_steer_motor_id: int = 5
    _front_left_encoder_id: int = 1
    _front_left_encoder_offset: units.rotation = -0.177978515625
    _front_left_steer_motor_inverted: bool = True
    _front_left_encoder_inverted: bool = False
    _front_left_x_pos: units.meter = 0.2585
    _front_left_y_pos: units.meter = 0.2585

    _front_right_drive_motor_id: int = 4
    _front_right_steer_motor_id: int = 8
    _front_right_encoder_id: int = 4
    _front_right_encoder_offset: units.rotation = -0.2197265625
    _front_right_steer_motor_inverted: bool = True
    _front_right_encoder_inverted: bool = False
    _front_right_x_pos: units.meter = 0.2585
    _front_right_y_pos: units.meter = -0.2585

    _back_left_drive_motor_id: int = 2
    _back_left_steer_motor_id: int = 6
    _back_left_encoder_id: int = 2
    _back_left_encoder_offset: units.rotation = -0.333251953125
    _back_left_steer_motor_inverted: bool = True
    _back_left_encoder_inverted: bool = False
    _back_left_x_pos: units.meter = -0.2585
    _back_left_y_pos: units.meter = 0.2585

    _back_right_drive_motor_id: int = 3
    _back_right_steer_motor_id: int = 7
    _back_right_encoder_id: int = 3
    _back_right_encoder_offset: units.rotation = 0.49462890625
    _back_right_steer_motor_inverted: bool = True
    _back_right_encoder_inverted: bool = False
    _back_right_x_pos: units.meter = -0.2585
    _back_right_y_pos: units.meter = -0.2585

    drivetrain_constants: swerve.SwerveDrivetrainConstants = field(init=False)
    _constants_creator: swerve.SwerveModuleConstantsFactory = field(init=False)
    front_left: swerve.SwerveModuleConstants = field(init=False)
    front_right: swerve.SwerveModuleConstants = field(init=False)
    back_left: swerve.SwerveModuleConstants = field(init=False)
    back_right: swerve.SwerveModuleConstants = field(init=False)

    def __post_init__(self) -> None:
        self.drivetrain_constants = (
            swerve.SwerveDrivetrainConstants()
            .with_can_bus_name(self.canbus.name)
            .with_pigeon2_id(self._pigeon_id)
            .with_pigeon2_configs(self._pigeon_configs)
        )

        self._constants_creator = (
            swerve.SwerveModuleConstantsFactory[
                configs.TalonFXConfiguration,
                configs.TalonFXConfiguration,
                configs.CANcoderConfiguration,
            ]()
            .with_drive_motor_gear_ratio(self._drive_gear_ratio)
            .with_steer_motor_gear_ratio(self._steer_gear_ratio)
            .with_coupling_gear_ratio(self._couple_ratio)
            .with_wheel_radius(self._wheel_radius)
            .with_steer_motor_gains(self._steer_gains)
            .with_drive_motor_gains(self._drive_gains)
            .with_steer_motor_closed_loop_output(self._steer_closed_loop_output)
            .with_drive_motor_closed_loop_output(self._drive_closed_loop_output)
            .with_slip_current(self._slip_current)
            .with_speed_at12_volts(self.speed_at_12_volts)
            .with_drive_motor_type(self._drive_motor_type)
            .with_steer_motor_type(self._steer_motor_type)
            .with_feedback_source(self._steer_feedback_type)
            .with_drive_motor_initial_configs(self._drive_initial_configs)
            .with_steer_motor_initial_configs(self._steer_initial_configs)
            .with_encoder_initial_configs(self._encoder_initial_configs)
            .with_steer_inertia(self._steer_inertia)
            .with_drive_inertia(self._drive_inertia)
            .with_steer_friction_voltage(self._steer_friction_voltage)
            .with_drive_friction_voltage(self._drive_friction_voltage)
        )

        self.front_left = self._constants_creator.create_module_constants(
            self._front_left_steer_motor_id,
            self._front_left_drive_motor_id,
            self._front_left_encoder_id,
            self._front_left_encoder_offset,
            self._front_left_x_pos,
            self._front_left_y_pos,
            self._invert_left_side,
            self._front_left_steer_motor_inverted,
            self._front_left_encoder_inverted,
        )
        self.front_right = self._constants_creator.create_module_constants(
            self._front_right_steer_motor_id,
            self._front_right_drive_motor_id,
            self._front_right_encoder_id,
            self._front_right_encoder_offset,
            self._front_right_x_pos,
            self._front_right_y_pos,
            self._invert_right_side,
            self._front_right_steer_motor_inverted,
            self._front_right_encoder_inverted,
        )
        self.back_left = self._constants_creator.create_module_constants(
            self._back_left_steer_motor_id,
            self._back_left_drive_motor_id,
            self._back_left_encoder_id,
            self._back_left_encoder_offset,
            self._back_left_x_pos,
            self._back_left_y_pos,
            self._invert_left_side,
            self._back_left_steer_motor_inverted,
            self._back_left_encoder_inverted,
        )
        self.back_right = self._constants_creator.create_module_constants(
            self._back_right_steer_motor_id,
            self._back_right_drive_motor_id,
            self._back_right_encoder_id,
            self._back_right_encoder_offset,
            self._back_right_x_pos,
            self._back_right_y_pos,
            self._invert_right_side,
            self._back_right_steer_motor_inverted,
            self._back_right_encoder_inverted,
        )
