---
name: Send Slack notifications

on:
  push:
    branches:
      - main
    paths:
      # Not exactly the same as pyproject.toml tool.robotpy but close enough
      - uv.lock

permissions:
  contents: read

jobs:
  deps:
    runs-on: ubuntu-slim

    steps:
      - uses: actions/checkout@v6

      - name: Check if tool.robotpy changed
        id: check
        env:
          BEFORE: ${{ github.event.before }}
        run: |
          extract_robotpy_table() {
            yq -p toml -oy '.tool.robotpy'
          }

          OLD="$(git show "$BEFORE":pyproject.toml | extract_robotpy_table)"
          NEW="$(extract_robotpy_table < pyproject.toml)"

          if [[ "$OLD" != "$NEW" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Post a message in a channel
        if: steps.check.outputs.changed == 'true'
        uses: slackapi/slack-github-action@v2
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: ":mega: Robot dependencies have been updated!"
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: >-
                    :mega: Robot dependencies have been updated! Please rebase all open PRs,
                    and download the new dependencies by following the
                    <${{ github.server_url }}/${{ github.repository }}#install-dependencies|instructions in the readme>.
              - type: "context"
                elements:
                  - type: "mrkdwn"
                    text: >-
                      Triggered on ${{ github.event_name }} for commit
                      <${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>
